### ISSUE TITLE
v0.2.0 todo

### ISSUE THREAD

**Issue by davi-alexandre** [davi-alexandre/leavify#1]
- [x] default export.
- [ ] Figure out why import intellisense sometimes keeps suggesting the dist folder.
- [x] write more tests, to cover the function arguments as well.
- [x] Change package description
- [x] start with the readme.
- [x] Rename the function toChangeSet, since it refers to the type Changes and not ChangeSet.
- [x] remove the type ChangeSet.
- [x] Consider removing the Change and Changes types.
- [x] Throw error instead of returning empty object in `get()` for the leaf values that do not exist; use `has()` instead.
- [x] Return the changed leaf instead of type Change in `findChanges()`, given it's a special case for the `mapLeaf()` argument and harder to programatically read.
- [x] Consider the return type of `toTree()`, as other than unknown. [object]
- [x] Add Branch type

**Comment by davi-alexandre** [comment]
About the weird imports directly to ./dist 
https://github.com/typescript-eslint/typescript-eslint/issues/5586
